# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wFDzpldjrKGetQG3yHN4Dz5rw6tFzwr_
"""

# Modello di Regressione Lineare
# Algoritmo supervisionato utilizzato per prevedere un valore continuo, dato un insieme di caratteristiche
#
# Principali step del modello:
# 1) Dataset sintetico: i dati vengono generati artificialmente con una relazione linearem più un pò di rumore casuale
# 2) Divisione del dataset: il dataset viene diviso in training set e test set per valutare il modello su dati non visti
# 3) Creazione e addestramento del modello: usiamo la LinearRegression da Scikit-learn per costruire il modello e addestrarlo con fit()
# 4) Valutazione: utilizziamo mean_squared_error per valutare la differenza tra i valori reali e quelli previsti, e r2_score per misurare quanto bene il modello spiega la varianza dei dati
# 5) Visualizzazione: il grafico finale mostra i dati reali e la linea di regressione
#
# Librerie: Scikit-learn, Matplotlib, Numpy
# 2024-09-30 - Andrea Cigliano


# Importiamo le librerie necessarie
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Creiamo un dataset sintetico (con una variabile indipendente)
np.random.seed(0)
X=2*np.random.rand(100,1)
y=4+3*X+np.random.randn(100,1)

# Dividiamo il dataset in training set e test set
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# Creaiamo il modello di Regressione Lineare
linear_model=LinearRegression()

# Addestriamo il modello sui dati di training
linear_model.fit(X_train,y_train)

# Prevediamo sui dati di test
y_pred=linear_model.predict(X_test)

# Calcoliamo l'errore quadratico medio (MSE) ed il coefficiente di determinazione (R2)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

# Stampa dei risultati
print(f"Errore quadratico medio (MSE): {mse}")
print(f"Coefficiente di determinazione (R2):{r2}")
print(f"Coefficiente del modello:{linear_model.coef_[0][0]}")
print(f"Intercetta del modello:{linear_model.intercept_[0]}")

# Visualizzazione dei risultati
plt.scatter(X_test,y_test, color="black", label="Dati reali")
plt.plot(X_test,y_pred,color="blue",linewidth=3,label="Regressione Lineare")
plt.xlabel("X")
plt.ylabel("y")
plt.legend()
plt.show()